### ISSUE TITLE
new Pupil objects don't initialise correctly

### ISSUE THREAD

**Issue by shmove** [shmove/team-3-group-project#4]
From what I can tell, Pupil objects are supposed to be initialised with UUID already set, but this doesn't seem to be the case. In addition, without manually initialising the 'TodoList' and 'Notes' properties the program will crash on trying to write student data.

https://github.com/shmove/team-3-group-project/blob/f6ee10dd47dbe08a7a66ac82c6da63ddc009f635/project/project/pupilRecords.cs#L368-L381

**Comment by Permille** [comment]
Check out the newest commit - I changed the arrangement of the constructor's parameters, and made the list generation automatic if they were not supplied in the constructor.
Normally, you shouldn't be using the Pupil constructor without any parameters - that should only be used if the pupil data isn't known at the time of the object's construction. Instead, use the other constructor that isn't marked as [Obsolete]. For an example of how to use this constructor, feel free to look at IPupilDataManager.cs:38: there, I still pass the empty lists at the end, but they are not required, and you can omit them in your code.
